### ISSUE TITLE
出现Module build failed

### ISSUE THREAD

**Issue by apersonw** [nikogu/roadhog-api-doc#14]
happy@happy:~/IdeaProjects/eg$ roadhog-api-doc start 8000

> roadhog-api-doc-boilerplate@ start /home/happy/IdeaProjects/eg/_roadhog-api-doc
> PORT=8000 ../node_modules/.bin/roadhog server

Starting the development server...

Failed to compile.

./src/api.js
Module build failed: ReferenceError: Unknown plugin "dva-hmr" specified in "base" at 3, attempted to resolve relative to "/home/happy/IdeaProjects/eg/_roadhog-api-doc/src"
    at Array.map (<anonymous>)

**Comment by apersonw** [comment]
编译成功了，原来是忘记npm install，但是roadhog-api-doc start 8000后只启动了api-doc，项目本身没有启动，好奇怪哦

**Comment by nikogu** [comment]
对，是两个服务，互相独立的
