### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by yamakasiluke** [nikogu/roadhog-api-doc#18]
multi ../node_modules/react-dev-utils/webpackHotDevClient.js ./src/index.js
Module not found: Can't resolve './src/index.js' in '/learn/quick-operation-platform-web/_roadhog-api-doc'

**Comment by meiyouqing** [comment]
I have the same problem! @yamakasiluke 
Anybody come to help?

**Comment by nikogu** [comment]
@yamakasiluke @meiyouqing  try `1.0.0`, and you can remove `_roadhog-api-doc` dir manually, and restart the command.
