### ISSUE TITLE
roadhog-api-doc start 报错

### ISSUE THREAD

**Issue by PatWu16** [nikogu/roadhog-api-doc#19]
roadhog 1.3.4
局部 roadhog-api-doc 0.2.11
全局 roadhog-api-doc 1.0.0

运行 roadhog-api-doc start 报错
![1517481544](https://user-images.githubusercontent.com/23301139/35674295-3456de44-077f-11e8-8702-68d5d0ba0e8a.jpg)
解决：
1、尝试将全局的 roadhog-api-doc版本指定安装0.2.x，但未能成功，仍然安装为1.0.0，
接着运行roadhog-api-doc start报同样的错误；
2、将自动生成的_roadhog-api-doc文件夹删除，再运行，无效；

请问是什么原因？

**Comment by PatWu16** [comment]
最后全局安装roadhog-api-doc 0.2.11成功，可以start，但build时报另外一个错
![image](https://user-images.githubusercontent.com/23301139/35710569-364a276e-07f3-11e8-83c8-946b0dc5017d.png)
尝试手动删除和命令行删除后，再build，错误依旧存在

**Comment by nikogu** [comment]
@PatWu16 升级到 1.0.0 啦，命令之前是不支持 windows 的

**Comment by nikogu** [comment]
局部的 roadhog 也要升级哦

**Comment by PatWu16** [comment]
@nikogu roadhog-api-doc1.0.0支持低版本的roadhog（1.x）吗？

**Comment by nikogu** [comment]
支持的，它本质上就是用你项目的依赖，在你的项目建立了一个查看 api 文档的小项目~
