### ISSUE TITLE
运行roadhog-api-doc static报错

### ISSUE THREAD

**Issue by LeeHarlan** [nikogu/roadhog-api-doc#20]
1. 在mac下1.0.0版本报以下错误信息：
    ```
    Failed to minify the bundle. Error: index.8de426fb.js from UglifyJs
    Unexpected token: operator (>) [index.8de426fb.js:189138,36]
    ```
    查找发现是[roadhog-api-doc/lib/utils.js](https://github.com/nikogu/roadhog-api-doc/blob/master/lib/utils.js#L7)文件第 7 行的箭头函数导致，这一段代码直接被打包到 
    index.8de426fb.js文件中
    ```
    Object.keys(proxy).forEach((key) => {
    ```
2. win10报以下错误信息：
    ```
    Error: EBUSY: resource busy or locked, rmdir 'xxx/_roadhog-api-doc'
    ````

**Comment by nikogu** [comment]
升级下你的 node 试试

**Comment by LeeHarlan** [comment]
mac版本v8.11.1
win10版本v8.7.0

**Comment by nikogu** [comment]
@LeeHarlan 你看看你的根项目是不是有 babel 的配置呀，roadhog-api-doc 读的是你当前项目的配置

**Comment by LeeHarlan** [comment]
没有配置。后面又把ant design pro的项目clone下来<code>git clone https://github.com/ant-design/ant-design-pro.git --depth=1</code>还是报一样的错误

**Comment by nikogu** [comment]
try `1.0.1`

**Comment by mengfei0053** [comment]
`Error: EBUSY: resource busy or locked, rmdir 'xxx/_roadhog-api-doc' `  我也报这个错了

**Comment by LeeHarlan** [comment]
@nikogu 还有let, setTimeout(() => {})，建议用babel做一个转换

@mengfei0053 
> Error: EBUSY: resource busy or locked, rmdir 'xxx/_roadhog-api-doc' 我也报这个错了

这个应该不是roadhog-api-doc的问题，[https://github.com/jprichardson/node-fs-extra/issues/532#issuecomment-366548307](https://github.com/jprichardson/node-fs-extra/issues/532#issuecomment-366548307)

**Comment by nikogu** [comment]
try `1.0.2`

**Comment by LeeHarlan** [comment]
mac环境已经没问题了
