### ISSUE TITLE
roadhog-api-doc Cannot find module 'babel-plugin-transform-decorators-legacy'

### ISSUE THREAD

**Issue by chenshuai2144** [nikogu/roadhog-api-doc#21]
babel 的新版本 不需要使用babel-plugin-transform-decorators-legacy 应该做个准备了

**Comment by nikogu** [comment]
https://github.com/nikogu/roadhog-api-doc/blob/master/boilerplate/.webpackrc#L4

就把这行删掉就完了哇

**Comment by nikogu** [comment]
@chenshuai2144 啥问题。。。?

**Comment by chenshuai2144** [comment]
![image](https://user-images.githubusercontent.com/8186664/41447958-93c734c2-708a-11e8-9722-e58a14ed9727.png)


估计是因为babel 转化的问题

**Comment by nikogu** [comment]
fixed:https://github.com/nikogu/roadhog-api-doc/commit/1bbd9d83fa136b497834c55cacd15266ea6c0fb2
