### ISSUE TITLE
关于 static 方法中的 request 模板配置

### ISSUE THREAD

**Issue by remotesc2** [nikogu/roadhog-api-doc#25]
本人在使用 antd pro 进行功能开发， roadhog-api-doc的 static 方法是写死了一个 request 模板。

但如果碰到一种情况：需要部分访问 mock 数据，部分访问真实数据的时候，就出现了问题，我现在的处理方法是直接修改 roadhog-api-doc/static.js 中的 tpl，是否可以考虑把这个模板改成配置文件的形式？

**Comment by nikogu** [comment]
确实有这个问题，一直想改没空改。

**Comment by remotesc2** [comment]
那有考虑过以某种方式的进行配置吗？
我可以提交 pr
我想到的就很简单粗暴了，在保留原有的访问 mock 数据的功能下，在 tpl 中增加一个占位符，支持外部的某个配置文件内容直接注入

**Comment by nikogu** [comment]
@remotesc2 其实很简单，就在当前目录下新建个 `roadhog_api_doc_request_tpl.js` 然后 `roadhog-api-doc` 发现当前目录有这个，就读取这个文件作为 request tpl 就好了。

**Comment by nikogu** [comment]
1.1.0 合了那个分支了
