### ISSUE TITLE
roadhog-api-doc在npm install后，${port}直接是原样输出的，导致无法启动

### ISSUE THREAD

**Issue by apersonw** [nikogu/roadhog-api-doc#8]
1、如果改为这样就可以运行了
"start": "${isWindows() ? `node ./win-start.js` : `PORT=9898 ../node_modules/.bin/roadhog server`}",
我是直接使用固定端口
2、有点奇怪的是，我看到动画中可以只启动一个，但是我却得另外npm start启动ant design pro；
3、下面的代码没有打印消息，
  // 5. 启动 roadhog
    exec('cd ' + tempDir + ' && npm start', function (err, stdout, stderr) {
      if (err) {
        throw new Error(err);
      } else {
        console.log(stdout);
      }
    });

**Comment by nikogu** [comment]
1. 第一个问题应该是 bug，我修改下
2. 第二个确实是要起两个服务的，两个都是独立运行的，互相没有关系
3. 打印消息这个我看看

**Comment by apersonw** [comment]
@nikogu 查了一些资料，process.exec是启动了一个shell，但是linux和macOS好像无法启动，这个函数无法执行，此处无法打印出来呢

**Comment by apersonw** [comment]
我打印出来的exec这个函数
ChildProcess {
  domain: null,
  _events: 
   { close: [Function: exithandler],
     error: [Function: errorhandler] },
  _eventsCount: 2,
  _maxListeners: undefined,
  _closesNeeded: 3,
  _closesGot: 0,
  connected: false,
  signalCode: null,
  exitCode: null,
  killed: false,
  spawnfile: '/bin/sh',
  _handle: Process { owner: [Circular], onexit: [Function], pid: 32688 },
  spawnargs: [ '/bin/sh', '-c', 'pwd' ],
  pid: 32688,
  stdin: 
   Socket {
     connecting: false,
     _hadError: false,
     _handle: 
      Pipe {
        bytesRead: 0,
        _externalStream: [External],
        fd: 12,
        writeQueueSize: 0,
        owner: [Circular],
        onread: [Function: onread],
        reading: true },
     _parent: null,
     _host: null,
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: false,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: null,
        encoding: null },
     readable: false,
     domain: null,
     _events: 
      { end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd] },
     _eventsCount: 3,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: true,
     allowHalfOpen: false,
     _bytesDispatched: 0,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: null,
     _server: null,
     [Symbol(asyncId)]: 44,
     [Symbol(bytesRead)]: 0 },
  stdout: 
   Socket {
     connecting: false,
     _hadError: false,
     _handle: 
      Pipe {
        bytesRead: 0,
        _externalStream: [External],
        fd: 14,
        writeQueueSize: 0,
        owner: [Circular],
        onread: [Function: onread],
        reading: true },
     _parent: null,
     _host: null,
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: true,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: [Object],
        encoding: 'utf8' },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        close: [Function],
        data: [Function: onChildStdout] },
     _eventsCount: 5,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: false,
     _bytesDispatched: 0,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: null,
     _server: null,
     [Symbol(asyncId)]: 45,
     [Symbol(bytesRead)]: 0 },
  stderr: 
   Socket {
     connecting: false,
     _hadError: false,
     _handle: 
      Pipe {
        bytesRead: 0,
        _externalStream: [External],
        fd: 16,
        writeQueueSize: 0,
        owner: [Circular],
        onread: [Function: onread],
        reading: true },
     _parent: null,
     _host: null,
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 0,
        pipes: null,
        pipesCount: 0,
        flowing: true,
        ended: false,
        endEmitted: false,
        reading: true,
        sync: false,
        needReadable: true,
        emittedReadable: false,
        readableListening: false,
        resumeScheduled: true,
        destroyed: false,
        defaultEncoding: 'utf8',
        awaitDrain: 0,
        readingMore: false,
        decoder: [Object],
        encoding: 'utf8' },
     readable: true,
     domain: null,
     _events: 
      { end: [Object],
        finish: [Function: onSocketFinish],
        _socketEnd: [Function: onSocketEnd],
        close: [Function],
        data: [Function: onChildStderr] },
     _eventsCount: 5,
     _maxListeners: undefined,
     _writableState: 
      WritableState {
        objectMode: false,
        highWaterMark: 16384,
        finalCalled: false,
        needDrain: false,
        ending: false,
        ended: false,
        finished: false,
        destroyed: false,
        decodeStrings: false,
        defaultEncoding: 'utf8',
        length: 0,
        writing: false,
        corked: 0,
        sync: true,
        bufferProcessing: false,
        onwrite: [Function: bound onwrite],
        writecb: null,
        writelen: 0,
        bufferedRequest: null,
        lastBufferedRequest: null,
        pendingcb: 0,
        prefinished: false,
        errorEmitted: false,
        bufferedRequestCount: 0,
        corkedRequestsFree: [Object] },
     writable: false,
     allowHalfOpen: false,
     _bytesDispatched: 0,
     _sockname: null,
     _pendingData: null,
     _pendingEncoding: '',
     server: null,
     _server: null,
     [Symbol(asyncId)]: 46,
     [Symbol(bytesRead)]: 0 },
  stdio: 
   [ Socket {
       connecting: false,
       _hadError: false,
       _handle: [Object],
       _parent: null,
       _host: null,
       _readableState: [Object],
       readable: false,
       domain: null,
       _events: [Object],
       _eventsCount: 3,
       _maxListeners: undefined,
       _writableState: [Object],
       writable: true,
       allowHalfOpen: false,
       _bytesDispatched: 0,
       _sockname: null,
       _pendingData: null,
       _pendingEncoding: '',
       server: null,
       _server: null,
       [Symbol(asyncId)]: 44,
       [Symbol(bytesRead)]: 0 },
     Socket {
       connecting: false,
       _hadError: false,
       _handle: [Object],
       _parent: null,
       _host: null,
       _readableState: [Object],
       readable: true,
       domain: null,
       _events: [Object],
       _eventsCount: 5,
       _maxListeners: undefined,
       _writableState: [Object],
       writable: false,
       allowHalfOpen: false,
       _bytesDispatched: 0,
       _sockname: null,
       _pendingData: null,
       _pendingEncoding: '',
       server: null,
       _server: null,
       [Symbol(asyncId)]: 45,
       [Symbol(bytesRead)]: 0 },
     Socket {
       connecting: false,
       _hadError: false,
       _handle: [Object],
       _parent: null,
       _host: null,
       _readableState: [Object],
       readable: true,
       domain: null,
       _events: [Object],
       _eventsCount: 5,
       _maxListeners: undefined,
       _writableState: [Object],
       writable: false,
       allowHalfOpen: false,
       _bytesDispatched: 0,
       _sockname: null,
       _pendingData: null,
       _pendingEncoding: '',
       server: null,
       _server: null,
       [Symbol(asyncId)]: 46,
       [Symbol(bytesRead)]: 0 } ] }

**Comment by nikogu** [comment]
windows 的问题，我这周看看，调一下兼容性

**Comment by huochezaodian** [comment]
multi ../node_modules/roadhog/node_modules/react-dev-utils/webpackHotDevClient.js ./src/api.js
Module not found: Can't resolve 'babel' in '_roadhog-api-doc'
我一直报这个错，是什么意思呀，很急，在线等

**Comment by apersonw** [comment]
@huochezaodian 现在这个模块还不支持linux，我原来也报过你这个

**Comment by nikogu** [comment]
@huochezaodian 建议用 cnpm 试试，npm 安装在一些场景会有问题

**Comment by huochezaodian** [comment]
@apersonw @nikogu 真的好了，谢谢了，我之前用的npm，但是我设置的taobao源，看来和cnpm效果还不一样，要去网上查查看为什么了，还有在.readhogrc.mock.js为什么不能请求node的原生模块，我用了fs就报错了，我删了就好了，0.0

**Comment by nikogu** [comment]
node 原生模块的问题，这个得去 [roadhog](https://github.com/sorrycc/roadhog) 看看了
